import "./globals.css";
import Button from "./components/Button";
import Image from "next/image";

export const metadata = {
	title: "Undangan Wisuda Darus-Sunnah",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="id">
			<body>
				<main className="relative flex items-center justify-center bg-zinc-800 h-screen overflow-hidden">
					<div className="relative flex items-center">
						<Image
							className="absolute right-[250px] animate-spin-slow z-0"
							src="/img/mandala-spin.png"
							alt="mandala"
							width={600}
							height={600}
						/>

						<div className="relative phone:w-[500px] w-screen bg-scroll h-screen bg-gradient-to-b from-zinc-700 to-zinc-950 shadow-2xl z-10 overflow-hidden border-x-2 border-[#E7C494] ">
							{/* <Image
								className="absolute z-20 pl-5"
								src="/img/rope.png"
								alt="garis"
								height={30}
								width={30}
							/> */}
							{children}
							<Image
								className="absolute -bottom-80 animate-reverse-spin -z-10"
								src="/img/mandala-spin.png"
								alt="mandala"
								width={600}
								height={600}
							/>
							{/* <Image
								className="absolute right-0 top-0 z-20 pr-5"
								src="/img/rope.png"
								alt="garis"
								height={30}
								width={30}
							/> */}
							<Button className="bottom-0" />
						</div>

						<Image
							className="absolute left-[250px] animate-reverse-spin z-0"
							src="/img/mandala-spin.png"
							alt="mandala"
							width={600}
							height={600}
						/>
					</div>
				</main>
			</body>
		</html>
	);
}
